name: Code Review

on:
  issue_comment:
    types: [created, edited]

jobs:
  code-review:
    runs-on: ubuntu-latest
    if: |
      github.event.comment.user.login == 'adshao' &&
      github.event.comment.body.startsWith('chatgpt:')
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: hmarr/debug-action@v2
    - name: OpenAI ChatGPT Code Review
      uses: ./
      with:
        LANGUAGE: 'English'
        PROGRAMMING_LANGUAGE: 'JavaScript'
        REVIEW_COMMENT_PREFIX: 'chatgpt:'
        FULL_REVIEW_COMMENT: 'chatgpt'
        OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
